### ISSUE TITLE
Figure Captions - Separate Paragraphs

### ISSUE THREAD

**Issue by ggarcia0596** [gettypubs/restoration-ancient-bronzes#4]
At this present time, figure captions cannot include separate paragraphs of text. Longer text captions cannot be broken into separate paragraphs which effects readability.

**Comment by geealbers** [comment]
For multiple paragraphs in YAML, you can use the pipe (`|`) character. So instead of having all the text in one block with double quotes, like this ...

```yaml
- id: "2.2"
  src: 2.2.jpg
  caption: "**Figure 2.2.** Installation view of the marble sculpture of Ferdinand IV as Minerva (inv. 10833), by Antonio Canova (Italian, 1757–1822), in the Museo Archeologico Nazionale, Naples. The statue was commissioned in 1800 and completed in 1816. It was set up in the alcove on the main staircase of the Real Museo Borbonico. On the unification of Italy it was removed from view, but was returned to the spot in 1997."
```

You instead use a pipe, and then go down a line and indent. Everything indented after the pipe will render as if a Markdown file, paragraphs and all. You can also include lists or blockquotes this way. Note that you don't use the double quotes around the text when using the pipe character.

```yaml
- id: "2.2"
  src: 2.2.jpg
  caption: |
    **Figure 2.2.** Installation view of the marble sculpture of Ferdinand IV as Minerva (inv. 10833), by Antonio Canova (Italian, 1757–1822), in the Museo Archeologico Nazionale, Naples. 
       
    The statue was commissioned in 1800 and completed in 1816. It was set up in the alcove on the main staircase of the Real Museo Borbonico. On the unification of Italy it was removed from view, but was returned to the spot in 1997.
```
